name: google_mobile_ads_example
description: Demonstrates how to use the google mobile ads plugin.

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads:
    path: ../

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0 <3.0.0"
