name: google_mobile_ads

on:
  pull_request:
    paths:
      - "packages/google_mobile_ads/**"
      - ".github/workflows/google_mobile_ads.yaml"
  push:
    branches:
      - master
    paths-ignore:
    - "docs/**"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*google_mobile_ads*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*google_mobile_ads_example*"

jobs:
  android:
    runs-on: macos-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh dev
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-example.sh android ./lib/main.dart
      - name: "Unit Tests"
        run: |
          cd packages/google_mobile_ads/example/android
          ./gradlew test

  apple:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh dev
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          flutter config --enable-macos-desktop
      - name: "Build iOS Example"
        run: ./.github/workflows/scripts/build-example.sh ios ./lib/main.dart
      - name: "Unit Tests"
        run: |
          cd packages/google_mobile_ads/ios
          pod lib lint --allow-warnings
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
